import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Stars from 'components/Stars'
import Footer from 'components/Footer'
import Experiences from 'components/Experiences'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <article className={styles.skillsArticle}>
          <img alt="Imagen pendiente" src=".." />
          <h2>Martin Gainza Koulaksezian</h2>
          <h3>Frontend Developer</h3>
          <div>
            <h4>Skills</h4>
            <ul className={styles.skillsList}>
              <li className={styles.skill}>
                <span>React</span>
                <Stars q={3} />
              </li>
            </ul>
          </div>
        </article>
        <section className={styles.rightSection}>
          <article className={styles.skillsArticle}>
            <h2>Projects</h2>
            <div className={styles.projectsContainer}>
              <div className={styles.project}>
              </div>
            </div>
          </article>
          <Experiences />
        </section>
      </main>
      <Footer />
    </div>
  )
}
